# Generated by Django 4.2 on 2023-05-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areaconocimiento',
            fields=[
                ('cod_area', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc_area', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_area', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'areaconocimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('cod_autor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('codigo_editorial', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(blank=True, max_length=30, null=True)),
                ('pagina_web', models.CharField(blank=True, max_length=200, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'editorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_empl', models.CharField(blank=True, max_length=60, null=True)),
                ('cargo_empl', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=60, null=True)),
                ('ano_publicacion', models.CharField(blank=True, max_length=4, null=True)),
                ('numero_pagina', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
                'ordering': ['isbn'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('num_prestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_realizacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_limite_devolucion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_entrega_devolucion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudlibronuevo',
            fields=[
                ('num_consecutivo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_solicitud', models.CharField(blank=True, max_length=200, null=True)),
                ('isbn', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo_libro', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'solicitudlibronuevo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, max_length=60, null=True)),
                ('email_usuario', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono_usuario', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
            ],
            options={
                'db_table': 'descarga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.libro')),
                ('formato', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('tamano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'digital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.libro')),
                ('num_ejemplar', models.IntegerField()),
                ('nom_sala', models.IntegerField(blank=True, null=True)),
                ('num_pasillo', models.IntegerField(blank=True, null=True)),
                ('num_estante', models.IntegerField(blank=True, null=True)),
                ('num_cajon', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ejemplar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escrito',
            fields=[
                ('cod_autor', models.OneToOneField(db_column='cod_autor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.autor')),
            ],
            options={
                'db_table': 'escrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('universidad', models.CharField(blank=True, max_length=60, null=True)),
                ('carrera', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('num_ejemplar', models.IntegerField()),
                ('desc_multa', models.IntegerField(blank=True, null=True)),
                ('valor_multa', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'multa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('num_prestamo', models.OneToOneField(db_column='num_prestamo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.prestamo')),
                ('num_ejemplar', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tiene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesorareadeinteres',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.profesor')),
                ('area_interes', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'profesorareadeinteres',
                'managed': False,
            },
        ),
    ]
