# Generated by Django 3.2.5 on 2023-05-19 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areaconocimiento',
            fields=[
                ('codigo_area', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('desc_area', models.CharField(max_length=50, verbose_name='Descripción')),
                ('nombre_area', models.CharField(max_length=20, verbose_name='Nombre')),
                ('cod_area_contenida', models.ForeignKey(db_column='cod_area_contenida', on_delete=django.db.models.deletion.DO_NOTHING, to='app.areaconocimiento', verbose_name='Código sub área')),
            ],
            options={
                'verbose_name_plural': 'Áreas de conocimiento',
                'db_table': 'areaconocimiento',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('codigo_autor', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('primer_nombre', models.CharField(max_length=40, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=40, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo apellido')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('codigo_editorial', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editorial', models.CharField(max_length=30, verbose_name='Nombre')),
                ('pagina_web', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('pais_origen', models.CharField(blank=True, max_length=30, null=True, verbose_name='País origen')),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
                'db_table': 'editorial',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=60)),
                ('cargo_empleado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('anio_publicacion', models.IntegerField(blank=True, null=True)),
                ('numero_pagina', models.IntegerField(blank=True, null=True)),
                ('codigo_area', models.ForeignKey(db_column='codigo_area', on_delete=django.db.models.deletion.DO_NOTHING, to='app.areaconocimiento')),
                ('codigo_editorial', models.ForeignKey(db_column='codigo_editorial', on_delete=django.db.models.deletion.DO_NOTHING, to='app.editorial')),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=60, verbose_name='Nombre')),
                ('email_usuario', models.CharField(max_length=60, verbose_name='Correo')),
                ('telefono_usuario', models.BigIntegerField(blank=True, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.libro', verbose_name='ISBN')),
                ('numero_ejemplar', models.IntegerField()),
                ('numero_sala', models.IntegerField()),
                ('numero_pasillo', models.IntegerField()),
                ('numero_estante', models.IntegerField()),
                ('numero_cajon', models.IntegerField()),
                ('disponibilidad', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ejemplares',
                'db_table': 'ejemplar',
                'unique_together': {('isbn', 'numero_ejemplar')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('universidad', models.CharField(max_length=60)),
                ('carrera', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Librodigital',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.libro')),
                ('formato', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(max_length=200)),
                ('tamano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Libros digitales',
                'db_table': 'librodigital',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('titulo', models.CharField(max_length=30)),
                ('dependencia', models.CharField(blank=True, max_length=30, null=True)),
                ('area_interes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Solicitudlibronuevo',
            fields=[
                ('num_consecutivo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_solicitud', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30)),
                ('titulo_libro', models.CharField(max_length=60)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='app.empleado')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='app.usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de nuevos libros',
                'db_table': 'solicitudlibronuevo',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('numero_prestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('fecha_limite_entrega', models.DateField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.empleado')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.estudiante')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
                'db_table': 'prestamo',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('numero_ejemplar', models.IntegerField()),
                ('descripcion_multa', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_multa', models.TextField(blank=True, null=True)),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, to='app.ejemplar')),
            ],
            options={
                'verbose_name_plural': 'Multas',
                'db_table': 'multa',
                'unique_together': {('id_usuario', 'isbn', 'numero_ejemplar')},
            },
        ),
        migrations.CreateModel(
            name='Libroescritoautor',
            fields=[
                ('codigo_autor', models.OneToOneField(db_column='codigo_autor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.autor')),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, to='app.libro')),
            ],
            options={
                'db_table': 'libroescritoautor',
                'unique_together': {('codigo_autor', 'isbn')},
            },
        ),
        migrations.CreateModel(
            name='Detalleprestamo',
            fields=[
                ('numero_prestamo', models.OneToOneField(db_column='numero_prestamo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.prestamo')),
                ('numero_ejemplar', models.IntegerField()),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, to='app.ejemplar')),
            ],
            options={
                'db_table': 'detalleprestamo',
                'unique_together': {('numero_prestamo', 'isbn', 'numero_ejemplar')},
            },
        ),
        migrations.CreateModel(
            name='Descargalibrodigital',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario', verbose_name='ID Usuario')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_descarga', models.DateTimeField(auto_now=True, verbose_name='Fecha de descarga')),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, to='app.librodigital', verbose_name='ISBN')),
            ],
            options={
                'db_table': 'descargalibrodigital',
                'unique_together': {('id_usuario', 'isbn')},
            },
        ),
    ]
