# Generated by Django 4.2 on 2023-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ejemplar_numero_cajon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='numero_cajon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de cajón'),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='numero_estante',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de estante'),
        ),
    ]
