# Generated by Django 4.2 on 2023-06-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_detalleprestamo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='app.autor'),
        ),
    ]
