# Generated by Django 4.2 on 2023-06-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_libro_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.areaconocimiento', verbose_name='Código de área'),
        ),
    ]
