# Generated by Django 4.2 on 2023-06-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_libro_codigo_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDigital',
            fields=[
                ('libro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.libro')),
                ('formato', models.CharField(max_length=30, verbose_name='Formato')),
                ('url', models.URLField(verbose_name='URL')),
                ('tamanio', models.IntegerField(verbose_name='Tamaño del Libro')),
            ],
            bases=('app.libro',),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='pagina_web',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ejemplar', models.IntegerField(verbose_name='Número ejemplar')),
                ('numero_sala', models.IntegerField(verbose_name='Número de sala')),
                ('numero_pasillo', models.IntegerField(verbose_name='Número de pasillo')),
                ('numero_estante', models.IntegerField(verbose_name='Número de estante')),
                ('numero_cajon', models.IntegerField(verbose_name='Número de cajón')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.libro')),
            ],
            options={
                'verbose_name_plural': 'Ejemplares',
                'db_table': 'ejemplar',
                'unique_together': {('libro', 'numero_ejemplar')},
            },
        ),
    ]
