# Generated by Django 4.2 on 2023-06-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_librodigital_alter_editorial_pagina_web_ejemplar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librodigital',
            options={'verbose_name_plural': 'Libros digitales'},
        ),
        migrations.AlterModelTable(
            name='librodigital',
            table='libro_digital',
        ),
    ]
