# Generated by Django 4.2 on 2023-06-20 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_librodigital_options_alter_librodigital_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconocimiento',
            name='codigo_area',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_code_area', message='Codigo no valido con el estandar, ejemplo: A01', regex='^a\\d{2}$')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='codigo_autor',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_code_area', message='Codigo no valido con el estandar, ejemplo: AUT01', regex='^aut\\d{2}$')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='codigo_editorial',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_code_area', message='Codigo no valido con el estandar, ejemplo: ED001', regex='^ed\\d{3}$')], verbose_name='ID'),
        ),
    ]
