# Generated by Django 4.2 on 2023-06-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_areaconocimiento_codigo_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconocimiento',
            name='desc_area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción'),
        ),
    ]
